#!/usr/bin/env bash
# Bash script that will display information about subdomains

display_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk -v subdomain="$subdomain" '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}'
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
        display_info "$1" "$subdomain"
    fi
done

