#!/usr/bin/env bash

display_info ()
{
    domain="$1"
    subdomain="$2"
    record_type=$(dig +short -t "$subdomain" "$domain")
    echo "The subdomain $subdomain is a $record_type record and points to $domain"
}

if [ "$#" -lt 1 ]; then
    echo "Error: Missing domain parameter"
    exit 1
fi

if [ "$#" -eq 1 ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"
    do
        display_info "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
else
    echo "Error: Too many arguments"
    exit 1
fi
