#!/usr/bin/env bash
# Script that configures a new Ubuntu machine with HAProxy load balancer

# Update package index and install necessary packages
apt-get -y update
apt-get install -y --no-install-recommends software-properties-common

# Add HAProxy repository and install HAProxy
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get install -y haproxy=2.8.\*

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
        bind *:80
        mode http
        default_backend Web_Servers
backend Web_Servers
        balance roundrobin
        mode http
        server 265123-web-01 54.157.172.41:80 check
        server 265123-web-02 54.174.165.251:80 check
EOF

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
service haproxy restart
