#!/usr/bin/env bash
# Write a Bash script that configures a server to the requirements below:
# -nginx is running and listening  on port 80 of all server'sactive IPv4 IPs

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
