#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8.

file=~/hosts.new
cp /etc/hosts $file
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g $file
cp -f $file /etc/hosts
